  - name: Install general apps
    hosts: localhost  
    tasks:
      # Kdiff3 is no longer avaialable in brew casks registry
      # - name: Install kdiff3
      #   homebrew_cask:
      #     name: kdiff3
      #     state: latest
      - name: install visual-studio-code
        homebrew_cask:
          name: visual-studio-code
          state: latest
      - name: Install vs code extensions
        shell:
          cmd: code --install-extension {{ item }}
        with_items:
          - dbaeumer.vscode-eslint 
          - DotJoshJohnson.xml 
          - humao.rest-client 
          - marlon407.code-groovy 
          - ms-azuretools.vscode-docker 
          - ms-dotnettools.csharp 
          - ms-python.python 
          - octref.vetur 
          - secanis.jenkinsfile-support 
          - syler.sass-indented 
          - sysoev.language-stylus
      - name: Install burp suite
        homebrew_cask:
          name: burp-suite
          state: present
      - name: Install wireshark
        homebrew:
          name: wireshark
          state: latest
      - name: Install mysqlclient
        homebrew:
          name: mysql-client
          state: latest
      - name: Install macpass
        homebrew_cask:
          name: macpass
          state: latest
      - name: install awscli
        pip:
          name: awscli
          executable: pip3
          state: latest
      - name: Install certbot
        homebrew:
          name: certbot
          state: latest
      - name: Install command line completion
        homebrew:
          name: bash-completion
          state: latest
      - name: install cntlm
        homebrew:
          name: cntlm
          state: latest
      - name: install docker-for-mac
        homebrew_cask:
          name: docker 
          state: latest
      - name: install node and npm
        homebrew:
          name: node
          state: latest

