  - name: Install general apps
    hosts: localhost
    tasks:
      - name: install cntlm
        homebrew:
          name: cntlm
          state: latest
      - name: install docker-for-mac
        homebrew_cask:
          name: docker 
          state: latest
      - name: install visual-studio-code
        homebrew_cask:
          name: visual-studio-code
          state: latest
      - name: install node and npm
        homebrew:
          name: node
          state: latest
      - name: install python and pip
        homebrew:
          name: python
          state: latest
      - name: install awscli
        pip:
          name: awscli
          executable: pip3
      - name: Install dotnet core sdk
        homebrew_cask:
          name: dotnet-sdk
          state: latest
      - name: Install kdiff3
        homebrew_cask:
          name: kdiff3
          state: latest
